const swaggerAutogen = require("swagger-autogen")();
const doc = {
  info: {
    version: "1.0.0",
    title: "RestAPI CA myTodo",
    description:
      "Documentation automatically generated by the <b>swaggerautogen</b> module.",
  },
  host: "localhost:3000",
  definitions: {
    Signup: {
      $name: "test user",
      $email: "test@gmail.com",
      $password: "0000",
    },
    Login: {
      $email: "test@gmail.com",
      $password: "0000",
    },
    Todo: {
      $name: "Course assignment",
      $description: "Complete the course assignment",
      $categoryId: 1,
      $statusId: 2,
    },
    Category: {
      $name: "School",
    },
    Authentication_format: {
      $authentication: "Bearer YOUR_ACCESS_TOKEN",
    },
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./app.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./bin/www");
});
